package zipengine

import (
	"archive/zip"
	"bytes"
	"fmt"
	"io"
	"time"
)

type FileItem struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

type ZipArchiveRequest struct {
	ArchiveName   string     `json:"archive_name"`
	IncludeReadme bool       `json:"include_readme"`
	ReadmeTitle   string     `json:"readme_title"`
	Files         []FileItem `json:"files"`
}

type ZipEngine struct{}

func NewZipEngine() *ZipEngine {
	return &ZipEngine{}
}

// CreateZipArchive compresses a list of in-memory files into a downloadable zip byte slice.
func (ze *ZipEngine) CreateZipArchive(req ZipArchiveRequest) ([]byte, error) {
	buf := new(bytes.Buffer)
	zipWriter := zip.NewWriter(buf)

	files := req.Files
	if req.IncludeReadme {
		readmeContent := fmt.Sprintf("# %s\n\nGenerated by Lopor Enterprise AI Workspace Engine on %s.\n\n## Included Files:\n",
			req.ReadmeTitle, time.Now().Format("2006-01-02 15:04:05"))
		for _, f := range req.Files {
			readmeContent += fmt.Sprintf("- `%s` (%d bytes)\n", f.Path, len(f.Content))
		}
		files = append([]FileItem{{Path: "README.md", Content: readmeContent}}, files...)
	}

	for _, file := range files {
		if file.Path == "" {
			continue
		}
		writer, err := zipWriter.Create(file.Path)
		if err != nil {
			return nil, fmt.Errorf("failed to create zip entry for %s: %w", file.Path, err)
		}
		_, err = io.WriteString(writer, file.Content)
		if err != nil {
			return nil, fmt.Errorf("failed to write zip content for %s: %w", file.Path, err)
		}
	}

	if err := zipWriter.Close(); err != nil {
		return nil, fmt.Errorf("failed to finalize zip archive: %w", err)
	}

	return buf.Bytes(), nil
}
